export const catImage = '/svg/cat.svg'
export const dogImage = '/svg/dog.svg'
export const authImage = '/svg/authentication.svg'
export const favouriteImage = '/svg/favourite.svg'
export const errorImage = '/svg/warning.svg'
export const logoImage = '/logo.png'
